import Head from 'next/head';
import React from 'react';
import HomeThreeMain from '../components/HomeThree/HomeThreeMain';
import FooterTwo from '../components/Layout/Footer/FooterTwo/FooterTwo';


export default function HomeThree() {

    return (
        <>
            <Head>
                <title>Oction - NFT Marketplace React, NextJs Template</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <HomeThreeMain />
            <FooterTwo />
        </>
    )
}
