import Head from 'next/head';
import React from 'react';
import HomeOneMain from '../components/HomeOne/HomeOneMain';
import Footer from '../components/Layout/Footer/FooterOne/Footer';
import Header from '../components/Layout/Header/Header';


export default function Home() {

  return (
    <>
      <Head>
        <title>Arythmatic - AI Generated NFT's</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header HeaderStatic="oc-transparent-header" />
      <HomeOneMain />
      <Footer />
    </>
  )
}
